<%@ Page Title="" Language="VB" MasterPageFile="~/adminmaster.master" AutoEventWireup="false" CodeFile="showplan.aspx.vb" Inherits="showplan" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
 <style>
      
 body
          {
              margin:1px;
               background:rgb(56,56,56);
               background-image:url("images/login.jpg"); 
                background-size:cover;
             

          }
          .dv
          {
              border:none;
              
              }
              .dv td
              {
                  border:none;
                  
                  }

</style>
    <center>
    <br />
    <br />
        <h1 style="color: #FFFFFF; font-size: 50px;">Show Data</h1>
         <asp:GridView ID="GridView1" runat="server" CssClass="dv" DataKeyNames="username" CellPadding="4" 
        GridLines="Horizontal" AutoGenerateDeleteButton="True" BackColor="White" 
            BorderColor="#CC9966" BorderStyle="Double" BorderWidth="1px" Width="600px">
             <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
             <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
             <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
             <RowStyle BackColor="White" BorderColor="Black" BorderStyle="Solid" 
                 ForeColor="#330099" HorizontalAlign="Center" />
             <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
             <SortedAscendingCellStyle BackColor="#FEFCEB" />
             <SortedAscendingHeaderStyle BackColor="#AF0101" />
             <SortedDescendingCellStyle BackColor="#F6F0C0" />
             <SortedDescendingHeaderStyle BackColor="#7E0000" />
    </asp:GridView>
   
  
   </center>

   
&nbsp;&nbsp; 
</asp:Content>

